### PR TITLE
:sparkles:: Add org-node-completion-at-point

### PR DESCRIPTION
**Pull request by cashpw**
1. Add integration with `completion-at-point`
2. Update relevant documentation

### CODE REVIEW

**Comment by meedstrom** [comment]
Thank you for this! I've been refactoring the codebase, which is why I've been reluctant to push a new version until tested, but I will merge this for sure.

**Comment by meedstrom** [comment]
@cashpw Have you by any chance done the FSF paperwork? I ask because I'm mulling over assigning the codebase to FSF, which means that even now I have to be mindful of "non-trivial contributions" :)

If not, not to worry, I'll write a capf.  It was still your submission that made it happen!

**Comment by cashpw** [comment]
> @cashpw Have you by any chance done the FSF paperwork? I ask because I'm mulling over assigning the codebase to FSF, which means that even now I have to be mindful of "non-trivial contributions" :)

I haven't filled out any paperwork for the Free Software Foundation.

Glad to see this committed! Did it exist prior to my pull request? I didn't know the abbreviation `capf` so I may have missed it when I looked through modes and functions.

**Comment by meedstrom** [comment]
It didn't exist, no.

**Comment by meedstrom** [comment]
@cashpw I've decided this project doesn't need to be FSF. So future PRs are welcome, for your info :)

**Pull request closed without merging**
