### PR TITLE
customisation for org-node-fakeroam-redisplay-mode

### PR DESCRIPTION
**Pull request by emacsomancer**
- add option to retain accelerations but disable autosync/follow

### CODE REVIEW

**Comment by meedstrom** [comment]
Oh OK, people want that?? :)

I guess then in Org-roam you used to do

    (remove-hook 'org-roam-find-file-hook #'org-roam-buffer--setup-redisplay-h)

?

**Comment by meedstrom** [comment]
I actually never understood quite how to use the org-roam buffer well.  Do people setup a dedicated window to show it always?  Do they bind `org-roam-buffer-toggle` and toggle twice for a quick glimpse every time they need to see it?

Do you want to see backlinks to a given buffer even though it is not the one you have in the other window?

**Comment by meedstrom** [comment]
Ahh, thanks for the use case.  I'll merge this, at least for people who toggle the buffer a lot and prefer the buffer to be less surprising (having ideas of a slightly better toggle command too).

But I'm liking the sound of `M-x org-roam-buffer-display-dedicated` too, for use cases like your perusal.  Have you tried it?  It creates a new buffer with a name like `"*org-roam: TITLE<FILENAME>*"` (source reproduced below), so maybe you can amend the `display-buffer-alist` rule so it also works on those.

Although you said perusal is the main thing you do so maybe it would just be unnecessary keystrokes.

**Comment by emacsomancer** [comment]
Oh, I haven't tried `M-x org-roam-buffer-display-dedicated`. Somehow I missed that. That does sound useful, as one could then have multiple backlinks buffers open.

Will the org-node optimisations still apply to the dedicated org-roam buffer?

**Comment by meedstrom** [comment]
I think it should.

**Comment by meedstrom** [comment]
Toggle command is yet another minor mode, so we have:

    (org-node-fakeroam-fast-render-mode) ;; accelerate things
    (org-node-fakeroam-redisplay-mode) ;; auto-refresh buffer

Sound good?

**Comment by meedstrom** [comment]
New command `org-node-fakeroam-show-roam-buffer` is what I had in mind.

**Pull request merged**
