### PR TITLE
revised optional Gregorian validity verification

### PR DESCRIPTION
**Pull request by emacsomancer**
- added `org-node-ensure-gregorian-validity` defcustom
  - Nb: left it off by default
- but if on, `org-node--example-daily-whereami` implements additional checks on both "NNNN-NN-NN" basenames and also on attempted `org-node-datestamp-format` putative dates to verify that they're valid Gregorian dates

[as per [previous discussion](https://github.com/meedstrom/org-node/pull/31), probably not *really* necessary, but it seemed like an interesting problem to solve, and this is at least less ugly than `^\\(?:[0-9][0-9]\\)\\{1,2\\}-\\(?:1[012]\\|0?[1-9]\\)-\\(?:0?[1-9]\\|[12][0-9]\\|3[01]\\)$`.]

(same as [other pull request](https://github.com/meedstrom/org-node/pull/33), but forgot to put in a branch)

### CODE REVIEW

**Comment by emacsomancer** [comment]
This makes sense. 

Though... what if there were a place for optional arbitrary checks? So the user could add their own function(s), if desired, for additional checks on a series item? 

Maybe not a priority, but it could be nice to have some sort of possible user-specifiable checking for series. The Gregorian thing is possibly too edge-case-y, but it could be the case for some series that it's less so.

**Comment by meedstrom** [comment]
I think then it'd make sense for the user to define a checker that they call from both their :classifier lambda and their :whereami lambda.

**Comment by emacsomancer** [comment]
After writing the above, I did begin to wonder if it might not be something that could be defined in `org-node-series-defs`.

Maybe I'll try to write up an example at some point using :classifier and :whereami that calls additional Gregorian checks as a model for what sorts of things could be in a user series definition.

**Comment by meedstrom** [comment]
> org-node-series-defs

You're very quick with keeping up with my renames! Do they bother you?

**Comment by emacsomancer** [comment]
since you have notification messages for them, they're not hard to deal with. and I think it's good to be able to adjust names to things that make sense as the project evolves.

**Pull request closed without merging**
